#!/usr/bin/env ruby
#!/usr/bin/env rake

require 'rake'
require 'gxl'
require 'jars_as_modules'

task :version do
  puts "Version 1.0"
end

task :extract => ['deps.xml', 'l1-names.pairs', 'modules-names.pairs']

desc "Dependencies extracted by Dependency Finder"
file 'deps.xml' => 'jars' do
  system "DependencyExtractor -xml -out deps.xml jars/*.jar"
end

file 'l1-names.pairs' => 'deps.xml' do
  depxml_to_pairs2('deps.xml', 'l1-names.pairs')
end

file 'modules-names.pairs' => 'jars' do
  pairs = extract_modules(Dir.glob("jars/*.jar"))
  puts_pairs(pairs, "modules-names.pairs")
end

task :numerize => ['l1-names.pairs', 'modules-names.pairs'] do
  system "to_numeric_network.rb l1-names.pairs modules-names.pairs l1-numbers.pairs modules-numbers.pairs"
end

directory 'jars'

task :analysis => :numerize do
end

task :stat_analysis => :analysis do
end

task :distance_matrix => :numerizacao do

end

task :clean do
  rm 'l1-names.pairs'
  rm 'modules-names.pairs'
  rm 'deps.xml'
end


#task :l1 => 'l1.pairs'
#
#task :analysis => [:l1] do
#  `analysis.rb`
#end
#
#task :stat_analysis => :analysis do
#  `stat_analysis.sh`
#end
#
#task :distances => :l1 do
#  `R --slave < ~/svn/swasr/sandbox/distances.R`
#end
#

if __FILE__ == $0; system "rake -f #{$0} #{ARGV.join(' ')}"; end
