#!/usr/bin/Rscript --vanilla

library(igraph)

argv = commandArgs(T)

if (length(argv) < 2){
  cat("This prints the 'distance' between two networks based on motif
frequencies, using chi-squared test.

Parameters: motif-data-1 motif-data-2

  The motif-data file are generated by motif.R.

")

  quit("no")
}

inputFile = argv[1]
outputFile = argv[2]

# TODO
